### PR TITLE
add Autorefresh if file permissions change

### LINKED ISSUE #7: Click on StatusBar to change File Access
Allow to change the File Access also clicking in the StatusBar item (today it only works as commands in Command Palette).

Just like I did in VSCode

### LINKED ISSUE #8: Autorefresh if file ReadOnly/Write mode is modified
Hello,

would be nice to have an automatic refresh of the status if the mode "ReadOnly/Write" of the file is modified.
Currently need to change the tabpage and comes back to update the status.
This is important that the status is always up to date, so that I can have confidence in this status and not always switch the tabpages to be sure I've an updated status.

### PR DESCRIPTION
**Pull request by jmtoniolo**
https://github.com/alefragnani/atom-read-only-indicator/issues/8

### CODE REVIEW

**Comment by jmtoniolo** [comment]
Actually after having used this a while it appears that fs.watch has a bug or something. Sometimes it just doesn't work at all. fs.watchFile has been working consistently but it seams a bit wasteful resource wise.

**Comment by alefragnani** [comment]
You could try `chokidar`. It appears to be _the_ alternative out there.

Also, once you noticed possible resource increase, I suggest you to add a `config` to enable/disable this _autorefresh_ feature. So, the user could choose to use that (opt-in), being warned about the resource it _can_ consume 😬 

What do you think?

**Comment by jmtoniolo** [comment]
Correct me if I'm wrong but chokidar appears to just be a wrapper class. I think if there is a bug in the current implementation of fs.watch then the problem may persist. I think I'll keep testing fs.watchFile for now (which has been working well) while I work on some settings options as you suggested.

**Comment by alefragnani** [comment]
Yes, but it says it “corrects some `fs` issues”.

> Node.js fs.watch:
>
>Doesn't report filenames on MacOS.
>Doesn't report events at all when using editors like Sublime on MacOS.
>Often reports events twice.
>Emits most changes as rename.
>Does not provide an easy way to recursively watch file trees.
>
>Node.js fs.watchFile:
>
>Almost as bad at event handling.
>Also does not provide any recursive watching.
>Results in high CPU utilization.
>
>Chokidar resolves these problems.

I remember VS Code has updated its `Filewatcher` last year, to use `chokidar`

**Comment by jmtoniolo** [comment]
I see. I'll have to add it as a dependency as it doesn't appear to be available for import with my current session. I'll search github for some examples.

**Comment by jmtoniolo** [comment]
Well, I think I got it. It has autorefresh capabilities with fs.watch (had trouble with chokidar.watch), AND I implemented the click icon to change r/w status. Plus menu options to disable each feature. Please let me know what you think.

**Comment by alefragnani** [comment]
That’s great! I’ll try to take a look/test by the weekend. If everything works ok, I should release a new release right after that.

Thank you

**Comment by alefragnani** [comment]
I’m not sure, but does `fs.chmod` work on Windows, today? 

I remember when I made this same extension to VS Code, and latter added the _change_ feature, I had to use `attrib` command, while on Windows.

**Comment by jmtoniolo** [comment]
I'm on windows 10 and fs.chmod has been working. I also have been testing it on my work computer which has a rather complicated source code manager that changes file write permissions for the current user and it works there too. Thank you for your time reviewing and testing I know I basically rewrote the view but I hope you like it and the features work flawlessly.

**Comment by alefragnani** [comment]
Hi @jmtoniolo ,

I just tested the PR and it is working _almost_ perfectly.

The settings are being respected, the Status Bar is updating as expected, and the Status Bar click is also updating the RW/RO status, _but_ I found an small issue at this point. 

When using the Status Bar click, the `chmod` applied is _changing_ permissions, other than the **user related**, when using on MacOS. This happens because the `00` from (`0o200` and `0o400`) you used, will update `group` and `other` permissions on *nix. You probably didn't noticed that because these values has no effect on Windows.

I guess you will have to use a similar approach from my other extension for VS Code. Instead of `fs.chmod`, I had to use `child_process.spawn`, to run `chmod` in shell. More info here:

https://github.com/alefragnani/vscode-read-only-indicator/blob/93679566018417ec28e08a59b0179c87a6104791/src/operations.ts#L30

Thank you

**Comment by jmtoniolo** [comment]
Thank you for the review. I'll fix it up soon and read up what you linked me to make sure it works on every OS.

**Comment by jmtoniolo** [comment]
Had a steep learning curve, but I think I have it. Tested it on a Debian virtual machine and Windows 10. Let me know how testing goes.

**Comment by alefragnani** [comment]
Sorry for taking so long to return to this. I had other priorities, but should return on this weekend.

I'll let you know how it goes.

Stay tuned

**Review by alefragnani — APPROVED** [review]

**Comment by jmtoniolo** [comment]
No problem alefragnani, I'm very excited that I was able to contribute. 
**Thank you for you time!**

**Comment by alefragnani** [comment]
In case you didn’t notice, the package was updated a few minutes ago 😬

Thank you for the contribution 👏

**Pull request merged**
